### ISSUE TITLE
using

### ISSUE THREAD

**Issue by pavel-b-novikov** [AMalininHere/nsudotnet#1]
using (var reader = new StreamReader(fileInfo.OpenRead()))
Ошибонька. В чем?

**Comment by AMalininHere** [comment]
Возможно был смысл использовать `fileInfo.OpenText`. Верно?

**Comment by pavel-b-novikov** [comment]
Нет

2015-03-26 17:05 GMT+06:00 Alexey Malinin <notifications@github.com>:

> Возможно был смысл использовать fileInfo.OpenText. Верно?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AMalininHere/nsudotnet/issues/1#issuecomment-86453128>
> .
>



-- 
Sincerelly yours,
Pavel B. Novikov
Skype: nsu_the_cjay
Phone: +7 961 872 5447

**Comment by pavel-b-novikov** [comment]
Ой, стоп. Акелла промахнулся. 
Технически ошибки нет, но объясните логику поведения StreamReader-а под using-ом?

**Comment by AMalininHere** [comment]
`using` для `IDisposable` освобождает ресурсы по выходу из `using` блока. Вызовется метод `Dispose` для `StreamReader`, который в свою очередь возовет `Dispose` для `Stream`, который в него передан.

**Comment by AMalininHere** [comment]
https://msdn.microsoft.com/ru-ru/library/yhfzs7at%28v=vs.110%29.aspx

**Comment by pavel-b-novikov** [comment]
Спасибо, я знаю где в MSDN статья про StreamReader, но речь не о том.
Речь о том, что в общем случае, если вы передаете disposable1 как аргумент
в disposable2 и тот сохраняет у себя ссылку на disposable1, то вызов
.Dispose у disposable1 вообще говоря не гарантируется по выходу из
using-блока. По сему рекомендуется оборачивать оба disposable-а в
usign-блоки (при том фигурный скорбки для первого disposable-а не нужны).

2015-03-26 17:22 GMT+06:00 Alexey Malinin <notifications@github.com>:

> https://msdn.microsoft.com/ru-ru/library/yhfzs7at%28v=vs.110%29.aspx
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AMalininHere/nsudotnet/issues/1#issuecomment-86464679>
> .
>



-- 
Sincerelly yours,
Pavel B. Novikov
Skype: nsu_the_cjay
Phone: +7 961 872 5447

**Comment by AMalininHere** [comment]
Извините.

**Comment by AMalininHere** [comment]
Большое спасибо за информацию. Исправил
